---

- name: Provision App Logic
  hosts: all

  vars:
    virtual_display_no: 99

  tasks:
    - name: Installing Nodejs repo
      shell: curl https://raw.githubusercontent.com/nodesource/distributions/master/deb/setup_8.x -o /tmp/setup_8.x && bash /tmp/setup_8.x

    - name: Installing packages
      apt: name="{{item}}" state=present update_cache=yes
      with_items:
        - nodejs

    - name: Install signingkey
      apt_key:
        url: https://dl-ssl.google.com/linux/linux_signing_key.pub
        state: present
   
    - name: Register chrome repo
      apt_repository:
        repo: deb http://dl.google.com/linux/chrome/deb/ stable main
        state: present
        filename: google-chrome        

    - name: Chrome headless packages
      apt: pkg="{{item}}" state="present" update_cache="yes"     
      with_items:
         - libxpm4 
         - libxrender1 
         - libgtk2.0-0 
         - libnss3 
         - libgconf-2-4
         - google-chrome-stable
         - gtk2-engines-pixbuf
         - xfonts-cyrillic 
         - xfonts-100dpi 
         - xfonts-75dpi 
         - xfonts-base 
         - xfonts-scalable
        
    - name: Installing http-backend-proxy through npm
      shell: npm install -g protractor http-backend-proxy    
    
    - name: Install Selenium and Chrome driver  
      shell: webdriver-manager update      

    - name: Add a non-privileged user for running Protrator
      shell:  adduser --home /project --uid 1100 --disabled-login --disabled-password --gecos node node      

    - name: template configs
      template: src="templates/{{item}}.conf.j2" dest="/etc/supervisor/conf.d/{{item}}.conf"
      with_items:
        #  - protractor
         - webdriver

    - name: install lodash moment jasmine-reporters
      shell: npm install lodash moment jasmine-reporters


- name: Container cleanup
  hosts: all
  gather_facts: no
  tasks:
    - name: Remove python
      raw:  apt-get autoremove -y && apt-get clean

    - name: Remove apt lists
      raw: rm -rf /var/lib/apt/lists/*
